services:
    postgres:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - '5438:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data

    minio:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001"
        env_file:
            - .env
        volumes:
            - minio-data:/data
        command: server /data --console-address ":9001"

    mailcatcher:
        image: dockage/mailcatcher
        ports:
            - '1025:1025'
            - '1080:1080'
volumes:
    postgres-data:
    minio-data:
