import '@swimetrics/utils/global.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import ClientSessionProvider from '../providers/ClientSessionProvider';

export const metadata = {
  title: 'Welcome to video-analyzer',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // if (!routing.locales.includes(locale as any)) {
  //   notFound();
  // }
  const messages = await getMessages();

  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
